# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Bump and Publish

on:
  release:
    types: [released]
    # refs/tags/x.x.x

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Test
        run: npm test

  bump-and-build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v3
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - run: npm --no-git-tag-version --allow-same-version version ${{ steps.get_version.outputs.VERSION }}
        working-directory: projects/ngx-google-analytics
      - run: npm run build
      - run: |
          cp LICENSE dist/ngx-google-analytics
          cp README.md dist/ngx-google-analytics
          cp CHANGELOG.md dist/ngx-google-analytics
      - run: npm pack
        working-directory: dist/ngx-google-analytics
      - name: 'Upload Build Artifact ${{ steps.get_version.outputs.VERSION }}'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.get_version.outputs.VERSION }}.tgz
          path: dist/ngx-google-analytics/hakimio-ngx-google-analytics-${{ steps.get_version.outputs.VERSION }}.tgz

  publish-npm:
    needs: bump-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ steps.get_version.outputs.VERSION }}.tgz
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/
      - run: npm publish --access public hakimio-ngx-google-analytics-${{ steps.get_version.outputs.VERSION }}.tgz
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
